"""Controller-neutral action interface for Experiment E02."""

from .action_interface import (
    ACTION_INTERFACE_VERSION,
    ActionEnvelope,
    CommonActionInterface,
    ControlTopology,
    ForbiddenInformationError,
    InformationPermission,
    PolicyNativeReadGateway,
    ReadCapability,
)
from .engine import (
    ExactParityResult,
    MatchedExecutionContract,
    TopologyRun,
    evaluate_no_fault_parity,
    run_with_contract,
)
from .architectures import (
    ARCHITECTURE_INTERFACE_VERSION,
    PRESPECIFICATION_SHA256,
    ArchitectureExecutionContract,
    ArchitectureRun,
    ControlArchitecture,
    CoordinatorDecision,
    CoordinatorProfile,
    CoordinatorSignal,
    FrozenWeakCoordinator,
    WeakCoordinatorParameters,
    coordinator_input_fields,
    exact_replay_architecture,
    run_architecture,
)

__all__ = [
    "ACTION_INTERFACE_VERSION",
    "ARCHITECTURE_INTERFACE_VERSION",
    "PRESPECIFICATION_SHA256",
    "ActionEnvelope",
    "ArchitectureExecutionContract",
    "ArchitectureRun",
    "CommonActionInterface",
    "ControlTopology",
    "ControlArchitecture",
    "CoordinatorDecision",
    "CoordinatorProfile",
    "CoordinatorSignal",
    "ExactParityResult",
    "ForbiddenInformationError",
    "FrozenWeakCoordinator",
    "InformationPermission",
    "MatchedExecutionContract",
    "PolicyNativeReadGateway",
    "ReadCapability",
    "TopologyRun",
    "WeakCoordinatorParameters",
    "coordinator_input_fields",
    "evaluate_no_fault_parity",
    "exact_replay_architecture",
    "run_architecture",
    "run_with_contract",
]
