"""Distance and path tools for the E03 detour experiment."""

from .distances import (
    DistanceProfile,
    adjacent_descents,
    distance_profile,
    duplicate_aware_earth_movers_distance,
    earth_movers_distance,
    inversion_count,
    maximum_duplicate_aware_earth_movers_distance,
    maximum_earth_movers_distance,
    maximum_inversion_count,
    maximum_possible_rank_error,
    maximum_rank_error,
    maximum_spearman_footrule,
    normalized_adjacent_descents,
    normalized_duplicate_aware_earth_movers_distance,
    normalized_earth_movers_distance,
    normalized_kendall_distance,
    normalized_maximum_rank_error,
    normalized_spearman_footrule,
    paper_sortedness_distance,
    paper_sortedness_strict,
    spearman_footrule,
)

__all__ = [
    "DistanceProfile",
    "adjacent_descents",
    "distance_profile",
    "duplicate_aware_earth_movers_distance",
    "earth_movers_distance",
    "inversion_count",
    "maximum_duplicate_aware_earth_movers_distance",
    "maximum_earth_movers_distance",
    "maximum_inversion_count",
    "maximum_possible_rank_error",
    "maximum_rank_error",
    "maximum_spearman_footrule",
    "normalized_adjacent_descents",
    "normalized_duplicate_aware_earth_movers_distance",
    "normalized_earth_movers_distance",
    "normalized_kendall_distance",
    "normalized_maximum_rank_error",
    "normalized_spearman_footrule",
    "paper_sortedness_distance",
    "paper_sortedness_strict",
    "spearman_footrule",
]
