"""State-matched barrier interventions for E03 S09.

The S05 graph is a finite structural opportunity graph, whereas E01 replay uses
scenario-keyed counter-addressed streams.  S09 therefore uses a typed external
schedule: actor and Bubble-side tokens are generated by the frozen E01 SHA-256
RNG under a pairing key shared by every arm.  Transition construction,
validation, commit, cost, terminal precedence, and event serialization remain
the authoritative E01 implementations.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
from typing import Any, Literal

from reference_simulator.engine import (
    EMPTY_DIGEST,
    execute_batch,
    evaluate_terminal,
)
from reference_simulator.model import (
    Architecture,
    Cell,
    FaultMode,
    Policy,
    Proposal,
    RunState,
    Scenario,
    canonical_json_bytes,
)
from reference_simulator.policies import cell_view_proposal
from reference_simulator.rng import bounded, u64
from reference_simulator.scheduler import ScheduledOpportunity
from reference_simulator.transition_primitives import ValidationDecision, ledger_identity
from src.detours.distances import distance_profile
from src.detours.state_space import FamilySpec, StructuralState, cell_id


SCHEMA_VERSION = "e03.s09.barrier_interventions.v1"
COUPLING_PROFILE = "sha256_counter_E01_v1_common_pair_key_conditioned_focal_event0"
METRICS = (
    "adjacent_descents",
    "inversion_count",
    "spearman_footrule",
    "maximum_rank_error",
)


def canonical_digest(value: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def structural_state_from_ordinal(family: FamilySpec, state_ordinal: int) -> StructuralState:
    occupancy_rank = int(state_ordinal) % math.factorial(family.n)
    cursor_code = int(state_ordinal) // math.factorial(family.n)
    return StructuralState(family, occupancy_rank, cursor_code)


def dynamic_state_payload(state: RunState) -> dict[str, Any]:
    """Scenario-independent mutable state used for cross-arm equality audits."""

    payload = state.to_dict()
    payload.pop("terminal")
    return payload


def dynamic_state_digest(state: RunState) -> str:
    return canonical_digest(dynamic_state_payload(state))


def metric_levels(scenario: Scenario, state: RunState) -> dict[str, int]:
    values = [scenario.cell_map[identity].value for identity in state.occupancy]
    direction = scenario.cells[0].direction.value
    profile = distance_profile(values, direction=direction)
    return {name: int(getattr(profile, name)) for name in METRICS}


def make_scenario(
    family: FamilySpec,
    *,
    seed: int,
    max_activations: int,
    generation_key: str,
) -> Scenario:
    cells = tuple(
        Cell(
            cell_id=cell_id(index),
            value=index,
            policy=family.policies[index],
            direction=family.direction,
            fault=family.faults[index],
        )
        for index in range(family.n)
    )
    return Scenario.create(
        cells,
        initial_occupancy=tuple(cell_id(index) for index in range(family.n)),
        seed=seed,
        max_activations=max_activations,
        architecture=family.architecture,
        scheduler=(
            "traditional_controller"
            if family.architecture == Architecture.TRADITIONAL
            else "serial_counter_addressed"
        ),
        batch_width=1,
        traditional_policy=(
            family.policies[0]
            if family.architecture == Architecture.TRADITIONAL
            else None
        ),
        generation_key=generation_key,
        fault_placement="explicit",
        requested_fault_count=family.fault_count,
    )


@dataclass(frozen=True, slots=True)
class CoupledToken:
    actor_index: int
    actor_id: str
    actor_draws: tuple[tuple[str, int, int, int], ...]
    actor_blocks: int
    raw_side: Literal["left", "right"]
    raw_side_value: int


def coupled_token(seed: int, coupling_key: str, event_index: int, n: int) -> CoupledToken:
    actor_index, consumed = bounded(
        seed, coupling_key, "actor_activation", event_index, n
    )
    actor_draws = tuple(
        (
            "actor_activation",
            event_index,
            draw_index,
            u64(seed, coupling_key, "actor_activation", event_index, draw_index),
        )
        for draw_index in range(consumed)
    )
    side_value = u64(seed, coupling_key, "bubble_side", event_index, 0)
    return CoupledToken(
        actor_index=actor_index,
        actor_id=cell_id(actor_index),
        actor_draws=actor_draws,
        actor_blocks=consumed,
        raw_side="left" if side_value < (1 << 63) else "right",
        raw_side_value=side_value,
    )


def conditioned_seed(
    coupling_key: str,
    focal_index: int,
    n: int,
    replicate_index: int,
) -> tuple[int, int]:
    """Find a deterministic 128-bit seed whose first actor is the barrier.

    Conditioning guarantees that the activation-pulse arm is delivered at the
    branch event.  The same conditioned event-0 opportunity is charged in every
    matched arm, and the untouched event-1+ counter-addressed remainder is
    shared exactly.
    """

    base = int.from_bytes(
        hashlib.sha256(
            f"E03/S09/seed/v1\x00{coupling_key}\x00{replicate_index}".encode()
        ).digest()[:16],
        "big",
    )
    for attempt in range(1_000_000):
        seed = (base + attempt) % (1 << 128)
        if coupled_token(seed, coupling_key, 0, n).actor_index == focal_index:
            return seed, attempt + 1
    raise RuntimeError("could not condition the first common actor on the focal barrier")


class _CoupledSchedule:
    def __init__(
        self,
        scenario: Scenario,
        *,
        coupling_key: str,
        seed: int,
        pulse_focal_id: str | None,
    ) -> None:
        self.scenario = scenario
        self.coupling_key = coupling_key
        self.seed = seed
        self.pulse_focal_id = pulse_focal_id

    def __call__(
        self, event_index: int, remaining_opportunities: int
    ) -> tuple[ScheduledOpportunity, ...]:
        if remaining_opportunities <= 0:
            return ()
        token = coupled_token(
            self.seed, self.coupling_key, event_index, len(self.scenario.cells)
        )
        actor = self.scenario.cell_map[token.actor_id]
        pulse = event_index == 0 and token.actor_id == self.pulse_focal_id
        consume_side = actor.policy == Policy.BUBBLE and (
            actor.fault == FaultMode.NORMAL or pulse
        )
        draws = list(token.actor_draws)
        consumption: list[tuple[str, int]] = [
            ("actor_activation", token.actor_blocks)
        ]
        bubble_side = None
        if consume_side:
            draws.append(("bubble_side", event_index, 0, token.raw_side_value))
            consumption.append(("bubble_side", 1))
            bubble_side = token.raw_side
        return (
            ScheduledOpportunity(
                actor_id=token.actor_id,
                random_draws=tuple(draws),
                stream_consumption=tuple(consumption),
                bubble_side=bubble_side,
            ),
        )


class _PulseProposalFactory:
    def __init__(self, temporary_scenario: Scenario, focal_id: str) -> None:
        self.temporary_scenario = temporary_scenario
        self.focal_id = focal_id

    def __call__(
        self,
        scenario: Scenario,
        state: RunState,
        actor_id: str,
        *,
        side: Literal["left", "right"] | None = None,
    ) -> Proposal:
        proposal_scenario = (
            self.temporary_scenario
            if state.activation_count == 0 and actor_id == self.focal_id
            else scenario
        )
        return cell_view_proposal(proposal_scenario, state, actor_id, side=side)


class _PulseInterceptor:
    def __init__(self, focal_id: str) -> None:
        self.focal_id = focal_id

    def prepare(
        self, proposal: Proposal, event_index: int
    ) -> tuple[Proposal, tuple[tuple[str, int], ...]]:
        return proposal, ()

    def outcome(
        self,
        proposal: Proposal,
        validation: ValidationDecision,
        event_index: int,
    ) -> ValidationDecision:
        if (
            event_index == 0
            and proposal.actor_id == self.focal_id
            and validation.decision == "rejected_actor_stuck"
        ):
            return ValidationDecision("valid", True)
        return validation

    def after_batch(
        self,
        scenario: Scenario,
        state: RunState,
        proposals: tuple[Proposal, ...],
        decisions: dict[int, str],
        batch_start_index: int,
    ) -> None:
        return None


def _temporary_activation_scenario(
    family: FamilySpec,
    focal_index: int,
    *,
    seed: int,
    max_activations: int,
    generation_key: str,
) -> Scenario:
    faults = list(family.faults)
    if faults[focal_index] != FaultMode.STUCK:
        raise ValueError("activation pulse requires a stuck focal identity")
    faults[focal_index] = FaultMode.NORMAL
    temporary = FamilySpec(
        n=family.n,
        architecture=family.architecture,
        direction=family.direction,
        policies=family.policies,
        faults=tuple(faults),
    )
    return make_scenario(
        temporary,
        seed=seed,
        max_activations=max_activations,
        generation_key=generation_key + ":pulse-temporary",
    )


def execute_intervention_arm(
    family: FamilySpec,
    state_ordinal: int,
    *,
    source_family_ordinal: int,
    arm_family_ordinal: int,
    intervention_type: str,
    arm_variant: str,
    focal_index: int,
    target_index: int | None,
    replicate_index: int,
    coupling_key: str,
    coupling_seed: int,
    seed_search_attempts: int,
    max_activations: int,
    retain_trace: bool = True,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Run one S09 arm from an exact structural state."""

    pulse = intervention_type == "activate"
    if pulse and family.architecture != Architecture.CELL_VIEW:
        raise ValueError("identity activation is undefined for traditional controllers")
    structural = structural_state_from_ordinal(family, state_ordinal)
    state = structural.to_run_state()
    pre_dynamic_hash = dynamic_state_digest(state)
    scenario = make_scenario(
        family,
        seed=coupling_seed,
        max_activations=max_activations,
        generation_key=(
            f"E03-S09:{source_family_ordinal}:{state_ordinal}:"
            f"{replicate_index}:{arm_variant}"
        ),
    )
    state.terminal = evaluate_terminal(scenario, state)
    initial_terminal = state.terminal or "active"
    levels = metric_levels(scenario, state)
    starts = dict(levels)
    peaks = dict(levels)
    worsening = {name: 0 for name in METRICS}
    trace: list[dict[str, Any]] = []
    digest = bytes.fromhex(EMPTY_DIGEST)

    proposal_factory = None
    interceptor = None
    pulse_focal = None
    if pulse:
        pulse_focal = cell_id(focal_index)
        temporary = _temporary_activation_scenario(
            family,
            focal_index,
            seed=coupling_seed,
            max_activations=max_activations,
            generation_key=scenario.generation_key,
        )
        proposal_factory = _PulseProposalFactory(temporary, pulse_focal)
        interceptor = _PulseInterceptor(pulse_focal)

    schedule = None
    if family.architecture == Architecture.CELL_VIEW:
        schedule = _CoupledSchedule(
            scenario,
            coupling_key=coupling_key,
            seed=coupling_seed,
            pulse_focal_id=pulse_focal,
        )

    pulse_delivered = False
    accepted_actions = 0
    while state.terminal is None:
        event_index = state.activation_count
        before_dynamic = dynamic_state_digest(state)
        before_levels = dict(levels)
        before_occupancy = tuple(state.occupancy)
        token = (
            coupled_token(coupling_seed, coupling_key, event_index, family.n)
            if family.architecture == Architecture.CELL_VIEW
            else None
        )
        events, encoded = execute_batch(
            scenario,
            state,
            retain_events=True,
            schedule_factory=schedule,
            proposal_factory=proposal_factory,
            execution_interceptor=interceptor,
        )
        if len(events) != 1 or len(encoded) != 1:
            raise AssertionError("S09 requires exactly one emitted serial opportunity")
        digest = hashlib.sha256(digest + encoded[0]).digest()
        event = events[0]
        levels = metric_levels(scenario, state)
        for name in METRICS:
            peaks[name] = max(peaks[name], levels[name])
            worsening[name] += int(levels[name] > before_levels[name])
        accepted = event["decision"] == "accepted"
        accepted_actions += int(accepted)
        delivered_now = pulse and event_index == 0 and event["actorId"] == pulse_focal
        pulse_delivered = pulse_delivered or delivered_now
        if retain_trace:
            trace.append(
                {
                    "event_index": event_index,
                    "actor_id": event["actorId"],
                    "raw_side": token.raw_side if token else None,
                    "raw_side_value": token.raw_side_value if token else None,
                    "side_consumed": any(
                        item["stream"] == "bubble_side"
                        for item in event["randomAddressesAndDraws"]
                    ),
                    "proposal_kind": event["proposal"]["kind"],
                    "proposal_reason": event["proposal"]["reason"],
                    "decision": event["decision"],
                    "pre_state_hash": event["preStateHash"],
                    "post_state_hash": event["postStateHash"],
                    "before_dynamic_hash": before_dynamic,
                    "after_dynamic_hash": dynamic_state_digest(state),
                    "before_occupancy": before_occupancy,
                    "after_occupancy": tuple(state.occupancy),
                    "before_levels": before_levels,
                    "after_levels": dict(levels),
                    "ledger_delta": dict(event["ledgerDelta"]),
                    "pulse_delivered": delivered_now,
                    "terminal": state.terminal,
                }
            )

    final_structural = StructuralState.from_run_state(family, state)
    compact_trace_digest = canonical_digest(trace)
    raw_actor_digest = canonical_digest(
        [(row["event_index"], row["actor_id"]) for row in trace]
    )
    raw_side_digest = canonical_digest(
        [(row["event_index"], row["raw_side_value"]) for row in trace]
    )
    run_id = "s09r:" + canonical_digest(
        {
            "sourceFamilyOrdinal": source_family_ordinal,
            "stateOrdinal": state_ordinal,
            "replicate": replicate_index,
            "armVariant": arm_variant,
            "couplingKey": coupling_key,
            "couplingSeed": str(coupling_seed),
        }
    )
    row: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "research_step_id": "S09",
        "run_id": run_id,
        "pair_block_id": f"{source_family_ordinal}:{state_ordinal}:{replicate_index}",
        "source_family_ordinal": source_family_ordinal,
        "source_state_ordinal": state_ordinal,
        "arm_family_ordinal": arm_family_ordinal,
        "arm_state_ordinal": state_ordinal,
        "n": family.n,
        "architecture": family.architecture.value,
        "direction": family.direction.value,
        "policy_profile": family.policy_profile,
        "intervention_type": intervention_type,
        "arm_variant": arm_variant,
        "focal_barrier_id": cell_id(focal_index),
        "target_cell_id": cell_id(target_index) if target_index is not None else None,
        "replicate_index": replicate_index,
        "coupling_profile": (
            COUPLING_PROFILE
            if family.architecture == Architecture.CELL_VIEW
            else "not_applicable_traditional_controller"
        ),
        "coupling_key": coupling_key,
        "coupling_seed": str(coupling_seed),
        "seed_search_attempts": seed_search_attempts,
        "event_budget": max_activations,
        "pre_dynamic_state_sha256": pre_dynamic_hash,
        "scenario_id": scenario.scenario_id,
        "initial_terminal": initial_terminal,
        "stop_reason": state.terminal,
        "completed": state.terminal == "complete",
        "event_budget_censored": state.terminal == "event_budget",
        "event_count": state.activation_count,
        "accepted_action_count": accepted_actions,
        "pulse_delivered": pulse_delivered if pulse else None,
        "final_state_ordinal": final_structural.selection_cursor_code
        * math.factorial(family.n)
        + final_structural.occupancy_rank,
        "final_dynamic_state_sha256": dynamic_state_digest(state),
        "event_digest_sha256": digest.hex(),
        "compact_trace_sha256": compact_trace_digest,
        "actor_token_prefix_sha256": raw_actor_digest,
        "side_token_prefix_sha256": raw_side_digest,
        "trace_complete": len(trace) == state.activation_count,
        "ledger_identities_valid": all(ledger_identity(state.ledger).values()),
        "full_ledger_unit_cost": sum(state.ledger.values()),
    }
    for key, value in state.ledger.items():
        row[f"cost_{key}"] = value
    for name in METRICS:
        row[f"start_{name}"] = starts[name]
        row[f"peak_{name}"] = peaks[name]
        row[f"excursion_{name}"] = peaks[name] - starts[name]
        row[f"final_{name}"] = levels[name]
        row[f"worsening_events_{name}"] = worsening[name]
    return row, trace


def compare_to_baseline(
    baseline_row: dict[str, Any],
    baseline_trace: list[dict[str, Any]],
    arm_row: dict[str, Any],
    arm_trace: list[dict[str, Any]],
) -> dict[str, Any]:
    common = min(len(baseline_trace), len(arm_trace))
    actor_match = all(
        baseline_trace[index]["actor_id"] == arm_trace[index]["actor_id"]
        for index in range(common)
    )
    side_match = all(
        baseline_trace[index]["raw_side_value"]
        == arm_trace[index]["raw_side_value"]
        for index in range(common)
    )

    def first_difference(field: str) -> int | None:
        for index in range(common):
            if baseline_trace[index][field] != arm_trace[index][field]:
                return index
        if len(baseline_trace) != len(arm_trace):
            return common
        return None

    result: dict[str, Any] = {
        "schema_version": "e03.s09.paired_effect.v1",
        "research_step_id": "S09",
        "pair_block_id": arm_row["pair_block_id"],
        "baseline_run_id": baseline_row["run_id"],
        "arm_run_id": arm_row["run_id"],
        "source_family_ordinal": arm_row["source_family_ordinal"],
        "source_state_ordinal": arm_row["source_state_ordinal"],
        "n": arm_row["n"],
        "architecture": arm_row["architecture"],
        "direction": arm_row["direction"],
        "policy_profile": arm_row["policy_profile"],
        "intervention_type": arm_row["intervention_type"],
        "arm_variant": arm_row["arm_variant"],
        "focal_barrier_id": arm_row["focal_barrier_id"],
        "target_cell_id": arm_row["target_cell_id"],
        "replicate_index": arm_row["replicate_index"],
        "pre_dynamic_state_equal": baseline_row["pre_dynamic_state_sha256"]
        == arm_row["pre_dynamic_state_sha256"],
        "common_prefix_event_count": common,
        "actor_token_common_prefix_equal": actor_match,
        "side_token_common_prefix_equal": side_match,
        "first_decision_divergence_event": first_difference("decision"),
        "first_dynamic_state_divergence_event": first_difference(
            "after_dynamic_hash"
        ),
        "first_side_consumption_divergence_event": first_difference(
            "side_consumed"
        ),
        "baseline_stop_reason": baseline_row["stop_reason"],
        "arm_stop_reason": arm_row["stop_reason"],
        "baseline_completed": baseline_row["completed"],
        "arm_completed": arm_row["completed"],
        "delta_completed": int(arm_row["completed"])
        - int(baseline_row["completed"]),
        "delta_activations": arm_row["cost_activations"]
        - baseline_row["cost_activations"],
        "delta_accepted_swaps": arm_row["cost_acceptedSwaps"]
        - baseline_row["cost_acceptedSwaps"],
        "delta_full_ledger_unit_cost": arm_row["full_ledger_unit_cost"]
        - baseline_row["full_ledger_unit_cost"],
    }
    for name in METRICS:
        result[f"delta_peak_{name}"] = (
            arm_row[f"peak_{name}"] - baseline_row[f"peak_{name}"]
        )
        result[f"delta_excursion_{name}"] = (
            arm_row[f"excursion_{name}"]
            - baseline_row[f"excursion_{name}"]
        )
        result[f"delta_final_{name}"] = (
            arm_row[f"final_{name}"] - baseline_row[f"final_{name}"]
        )
    return result


def family_with_faults(family: FamilySpec, faults: tuple[FaultMode, ...]) -> FamilySpec:
    return FamilySpec(
        n=family.n,
        architecture=family.architecture,
        direction=family.direction,
        policies=family.policies,
        faults=faults,
    )


def intervention_families(
    family: FamilySpec, focal_index: int
) -> list[tuple[str, str, int | None, FamilySpec]]:
    """Enumerate every isolated persistent arm plus the cell-view pulse arm."""

    if family.faults[focal_index] != FaultMode.STUCK:
        raise ValueError("focal identity must be the unique stuck barrier")
    if family.fault_count != 1:
        raise ValueError("S09 intervention families require exactly one barrier")
    normal_targets = [
        index for index, fault in enumerate(family.faults) if fault == FaultMode.NORMAL
    ]
    arms: list[tuple[str, str, int | None, FamilySpec]] = [
        ("baseline", "baseline", None, family)
    ]
    removed = list(family.faults)
    removed[focal_index] = FaultMode.NORMAL
    arms.append(
        ("remove", f"remove:{cell_id(focal_index)}", None, family_with_faults(family, tuple(removed)))
    )
    if family.architecture == Architecture.CELL_VIEW:
        arms.append(("activate", f"activate:{cell_id(focal_index)}:event0", None, family))
    for target in normal_targets:
        moved = list(family.faults)
        moved[focal_index] = FaultMode.NORMAL
        moved[target] = FaultMode.STUCK
        arms.append(
            (
                "move",
                f"move:{cell_id(focal_index)}->{cell_id(target)}",
                target,
                family_with_faults(family, tuple(moved)),
            )
        )
        added = list(family.faults)
        added[target] = FaultMode.STUCK
        arms.append(
            (
                "add",
                f"add:{cell_id(target)}",
                target,
                family_with_faults(family, tuple(added)),
            )
        )
    return arms

