"""Outcome-independent forensic helpers for the S12Y clock-domain audit.

This module is diagnostic only.  It deliberately provides no episode runner,
production projection, estimator replacement, or cache reader.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from typing import Any

import pandas as pd

from src.spatial_transfer.estimator_feasibility import (
    ENDPOINT_SPECS,
    STATUS_CONTRACTS,
    EstimatorFeasibilityError,
    endpoint_applies,
    project_endpoint_value,
)


@dataclass(frozen=True)
class RepresentationCase:
    case_id: str
    value: Any
    field_present: bool = True
    category: str = "synthetic"


REPRESENTATION_CASES = (
    RepresentationCase("missing_absent", None, field_present=False, category="missing"),
    RepresentationCase("explicit_null", None, category="missing"),
    RepresentationCase("pandas_missing", pd.NA, category="missing"),
    RepresentationCase("boolean_false", False, category="invalid_type"),
    RepresentationCase("boolean_true", True, category="invalid_type"),
    RepresentationCase("negative_two", -2, category="negative_integer"),
    RepresentationCase(
        "pre_transition_initial_sentinel",
        -1,
        category="negative_integer",
    ),
    RepresentationCase("negative_fractional", -0.5, category="fractional"),
    RepresentationCase("zero_integer", 0, category="boundary"),
    RepresentationCase("zero_float", 0.0, category="integer_valued_float"),
    RepresentationCase("one_integer", 1, category="interior"),
    RepresentationCase("interior_integer", 17, category="interior"),
    RepresentationCase("boundary_31", 31, category="boundary"),
    RepresentationCase("censor_boundary_32", 32, category="boundary"),
    RepresentationCase("beyond_horizon_33", 33, category="beyond_horizon"),
    RepresentationCase("positive_fractional", 1.5, category="fractional"),
    RepresentationCase("negative_infinity", -math.inf, category="nonfinite"),
    RepresentationCase("positive_infinity", math.inf, category="nonfinite"),
    RepresentationCase("nan", math.nan, category="nonfinite"),
    RepresentationCase("numeric_string", "17", category="string"),
    RepresentationCase("sentinel_string", "NOT_OBSERVED", category="string"),
)


def _row_for_status(
    status: str,
    representation: RepresentationCase,
) -> dict[str, Any]:
    flags = STATUS_CONTRACTS[status]
    row: dict[str, Any] = {
        "status": status,
        "endpointAvailable": flags["endpointAvailable"],
        "failed": flags["failed"],
        "censored": flags["censored"],
        "diagnostic": flags["diagnostic"],
    }
    if representation.field_present:
        row["firstCompletionTransition"] = representation.value
    return row


def _json_safe_value(value: Any) -> Any:
    if value is pd.NA:
        return {"syntheticScalar": "pandas.NA"}
    if isinstance(value, float) and not math.isfinite(value):
        if math.isnan(value):
            return {"syntheticScalar": "NaN"}
        return {"syntheticScalar": "+Infinity" if value > 0 else "-Infinity"}
    return value


def source_reachability(case_id: str) -> Mapping[str, Any]:
    """Return algebraic reachability without consulting an episode outcome."""

    if case_id == "pre_transition_initial_sentinel":
        return {
            "dslAdapter": True,
            "nativeBaseline": False,
            "authoritativeElapsedClock": False,
            "basis": "DSL adapter labels the pre-transition observation -1",
        }
    if case_id in {
        "zero_integer",
        "one_integer",
        "interior_integer",
        "boundary_31",
    }:
        return {
            "dslAdapter": True,
            "nativeBaseline": True,
            "authoritativeElapsedClock": case_id != "zero_integer",
            "basis": "loop index 0..31 is forwarded after a committed transition",
        }
    if case_id in {"missing_absent", "explicit_null"}:
        return {
            "dslAdapter": True,
            "nativeBaseline": True,
            "authoritativeElapsedClock": True,
            "basis": "no completion observation is represented as null",
        }
    if case_id == "censor_boundary_32":
        return {
            "dslAdapter": False,
            "nativeBaseline": False,
            "authoritativeElapsedClock": True,
            "basis": "32 is produced by the estimator's fixed right-censor projection",
        }
    return {
        "dslAdapter": False,
        "nativeBaseline": False,
        "authoritativeElapsedClock": False,
        "basis": "not generated by the ordinary frozen tracker/loop construction",
    }


def evaluate_case(status: str, representation: RepresentationCase) -> dict[str, Any]:
    """Exercise the frozen S12W projector for one synthetic state."""

    if status not in STATUS_CONTRACTS:
        raise ValueError(f"unknown synthetic status: {status}")
    spec = ENDPOINT_SPECS["restricted_native_transition_time_at_32"]
    applies = endpoint_applies(spec.endpoint_kind, status)
    result: dict[str, Any] = {
        "status": status,
        "representationId": representation.case_id,
        "representationCategory": representation.category,
        "fieldPresent": representation.field_present,
        "syntheticValue": _json_safe_value(representation.value),
        "endpointApplies": applies,
        **source_reachability(representation.case_id),
    }
    if not applies:
        result.update(
            {
                "disposition": "non_evidentiary_status_outside_endpoint_domain",
                "projectedValue": None,
                "errorType": None,
                "message": None,
            }
        )
        return result

    try:
        projected = project_endpoint_value(
            _row_for_status(status, representation),
            spec,
        )
    except EstimatorFeasibilityError as exc:
        result.update(
            {
                "disposition": "fail_closed",
                "projectedValue": None,
                "errorType": type(exc).__name__,
                "message": str(exc),
            }
        )
    else:
        result.update(
            {
                "disposition": "finite_projection",
                "projectedValue": float(projected),
                "errorType": None,
                "message": None,
            }
        )
    return result


def build_synthetic_matrix(
    *,
    statuses: Iterable[str] | None = None,
    representations: Iterable[RepresentationCase] = REPRESENTATION_CASES,
    reverse: bool = False,
) -> list[dict[str, Any]]:
    """Build the exhaustive status-by-representation matrix deterministically."""

    status_values = list(statuses or STATUS_CONTRACTS)
    representation_values = list(representations)
    pairs = [
        (status, representation)
        for status in status_values
        for representation in representation_values
    ]
    if reverse:
        pairs.reverse()
    rows = [evaluate_case(status, representation) for status, representation in pairs]
    return sorted(rows, key=lambda row: (row["status"], row["representationId"]))


def matrix_summary(rows: Iterable[Mapping[str, Any]]) -> dict[str, Any]:
    materialized = [dict(row) for row in rows]
    counts: dict[str, int] = {}
    for row in materialized:
        disposition = str(row["disposition"])
        counts[disposition] = counts.get(disposition, 0) + 1
    exact_domain_errors = sum(
        row.get("message")
        == "firstCompletionTransition must be an integer in [0,32]"
        for row in materialized
    )
    source_reachable_domain_errors = sum(
        row.get("message")
        == "firstCompletionTransition must be an integer in [0,32]"
        and (row["dslAdapter"] or row["nativeBaseline"])
        for row in materialized
    )
    return {
        "rowCount": len(materialized),
        "statusCount": len({str(row["status"]) for row in materialized}),
        "representationCount": len(
            {str(row["representationId"]) for row in materialized}
        ),
        "dispositionCounts": dict(sorted(counts.items())),
        "exactRecordedErrorClassCount": exact_domain_errors,
        "sourceReachableRecordedErrorClassCount": source_reachable_domain_errors,
    }


def native_clock_domains() -> dict[str, Any]:
    """Algebraic clock domains implied by the frozen source and E06 state."""

    return {
        "authoritativeMovementStateElapsedTransitionCount": {
            "initial": 0,
            "afterCommittedTransitionI": "i+1",
            "episodeDomain": [0, 32],
        },
        "dslTrackerArgument": {
            "initial": -1,
            "afterCommittedTransitionI": "i",
            "ordinaryDomain": "[-1,31] union {null}",
        },
        "nativeBaselineTrackerArgument": {
            "initial": "not_observed",
            "afterCommittedTransitionI": "i",
            "ordinaryDomain": "[0,31] union {null}",
        },
        "persistedProjection": "raw tracker value copied without normalization",
        "S12WRestrictedEndpoint": {
            "initialCompletion": 0,
            "postTransitionCompletion": "elapsed transition count",
            "noncompletion": 32,
            "domain": "[0,32]",
        },
    }
