"""Utilities for E07 Platonic-space corpus construction."""

from .behavior_corpus import build_behavior_corpus, validate_behavior_corpus
from .behavior_predictor import build_modeling_frame, target_coverage, train_evaluate_predictor
from .counterfactual_tests import (
    score_heldout_predictions,
    select_counterfactual_candidates,
    validate_candidates,
)
from .empirical_laws import (
    EMPIRICAL_LAW_CLAIM_BOUNDARY,
    EMPIRICAL_LAW_MODEL_VERSION,
    EMPIRICAL_LAW_SCHEMA_VERSION,
    build_anchor_metrics,
    build_empirical_law_synthesis,
    law_outcome_classification,
    validation_checks as validate_empirical_law_outputs,
)
from .goal_embeddings import build_goal_profiles, fit_goal_embedding
from .goal_catalog import build_goal_catalog, goal_schema_document, validate_goal_catalog
from .invariant_search import build_invariant_feature_frame, cross_world_holdout_search
from .inverse_design import (
    INVERSE_DESIGN_CLAIM_BOUNDARY,
    INVERSE_DESIGN_MODEL_VERSION,
    INVERSE_DESIGN_SCHEMA_VERSION,
    build_inverse_design_target_profiles,
    generate_inverse_design_pool,
    holdout_panel,
    nearest_existing_policy_comparison,
    policy_outcome_classification,
    reference_policy_table,
    run_design_panel,
    score_candidate_pool,
    select_designed_policies,
    s11_support_table,
    summarize_profile_validation,
    training_panel,
    validation_checks as validate_inverse_design_outputs,
    write_designed_policy_files,
)
from .periodic_table import (
    PERIODIC_TABLE_CLAIM_BOUNDARY,
    PERIODIC_TABLE_MODEL_VERSION,
    PERIODIC_TABLE_SCHEMA_VERSION,
    S13_S14_CAVEAT,
    build_periodic_table_bundle,
    extract_html_links,
    periodic_table_outcome_classification,
    render_periodic_table_html,
    validate_periodic_table_outputs,
)
from .platonic_distances import build_world_profiles, fit_world_embedding, pairwise_distance_tables
from .policy_embeddings import build_policy_profiles, fit_behavior_embedding, target_error_weights
from .policy_catalog import build_policy_catalog, validate_policy_catalog
from .substrate_transfer import (
    SUBSTRATE_TRANSFER_CLAIM_BOUNDARY,
    SUBSTRATE_TRANSFER_MODEL_VERSION,
    SUBSTRATE_TRANSFER_SCHEMA_VERSION,
    annotate_s08_transfer_distances,
    build_branch_graph_target,
    build_transfer_policy_panel,
    build_transfer_target_panel,
    distance_prediction_correlations,
    run_transfer_panel,
    summarize_transfer_runs,
    transfer_mapping_contract,
    transfer_outcome_classification,
    validation_checks as validate_substrate_transfer_outputs,
)
from .universality_classes import build_policy_taxonomy_features, build_taxonomy_tables
from .world_schema import (
    SCHEMA_VERSION,
    build_world_catalog,
    catalog_to_dataframe,
    validate_world_catalog,
    world_schema_document,
)

__all__ = [
    "SCHEMA_VERSION",
    "build_anchor_metrics",
    "build_behavior_corpus",
    "build_empirical_law_synthesis",
    "build_goal_profiles",
    "build_goal_catalog",
    "build_invariant_feature_frame",
    "build_inverse_design_target_profiles",
    "build_modeling_frame",
    "build_periodic_table_bundle",
    "build_policy_profiles",
    "build_policy_catalog",
    "build_policy_taxonomy_features",
    "build_branch_graph_target",
    "build_transfer_policy_panel",
    "build_transfer_target_panel",
    "build_taxonomy_tables",
    "build_world_profiles",
    "build_world_catalog",
    "catalog_to_dataframe",
    "cross_world_holdout_search",
    "generate_inverse_design_pool",
    "fit_goal_embedding",
    "fit_behavior_embedding",
    "fit_world_embedding",
    "pairwise_distance_tables",
    "score_heldout_predictions",
    "select_counterfactual_candidates",
    "goal_schema_document",
    "holdout_panel",
    "nearest_existing_policy_comparison",
    "policy_outcome_classification",
    "reference_policy_table",
    "run_design_panel",
    "run_transfer_panel",
    "score_candidate_pool",
    "select_designed_policies",
    "s11_support_table",
    "summarize_profile_validation",
    "summarize_transfer_runs",
    "target_coverage",
    "target_error_weights",
    "train_evaluate_predictor",
    "training_panel",
    "validate_candidates",
    "validate_empirical_law_outputs",
    "validate_inverse_design_outputs",
    "validate_substrate_transfer_outputs",
    "validate_behavior_corpus",
    "validate_goal_catalog",
    "validate_periodic_table_outputs",
    "validate_policy_catalog",
    "validate_world_catalog",
    "world_schema_document",
    "write_designed_policy_files",
    "annotate_s08_transfer_distances",
    "distance_prediction_correlations",
    "transfer_mapping_contract",
    "transfer_outcome_classification",
    "SUBSTRATE_TRANSFER_CLAIM_BOUNDARY",
    "SUBSTRATE_TRANSFER_MODEL_VERSION",
    "SUBSTRATE_TRANSFER_SCHEMA_VERSION",
    "INVERSE_DESIGN_CLAIM_BOUNDARY",
    "INVERSE_DESIGN_MODEL_VERSION",
    "INVERSE_DESIGN_SCHEMA_VERSION",
    "EMPIRICAL_LAW_CLAIM_BOUNDARY",
    "EMPIRICAL_LAW_MODEL_VERSION",
    "EMPIRICAL_LAW_SCHEMA_VERSION",
    "law_outcome_classification",
    "PERIODIC_TABLE_CLAIM_BOUNDARY",
    "PERIODIC_TABLE_MODEL_VERSION",
    "PERIODIC_TABLE_SCHEMA_VERSION",
    "S13_S14_CAVEAT",
    "extract_html_links",
    "periodic_table_outcome_classification",
    "render_periodic_table_html",
]
